name: Build and Deploy Demo

permissions:
  contents: write

on:
  push:
    branches: [ master ]

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Demo Files
        run: |
          mkdir -p demo
          cp index.html demo/
          cp fichier.js demo/
          cp style.css demo/
          echo "window.isDemo = true;" >> demo/fichier.js

      - name: Deploy Demo to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: demo
          clean: true